"""
Data exploration of raw nba data using python and pandas
"""
import pandas as pd

player_stats = pd.read_csv('../data/raw/player_stats.csv')
team_stats = pd.read_csv("../data/raw/team_stats.csv")
advanced_stats = pd.read_csv("../data/raw/advanced_player_stats.csv")
all_players = pd.read_csv("../data/raw/all_players_info.csv")
all_teams = pd.read_csv("../data/raw/all_teams_info.csv")

print("Player Stats Sample:")
print(player_stats.head())
print("\nPlayer Stats Description:")
print(player_stats.describe())
print("\nPlayer Stats Columns:")
print(player_stats.columns)
print("\nPlayer Stats Rows:")
print(len(player_stats))
print("\nPlayer Stats Missing Values:")
print(player_stats.isnull().sum())
print("-"*50)
print("\nTeam Stats Sample:")
print(team_stats.head())
print("\nTeam Stats Description:")
print(team_stats.describe())
print("\nTeam Stats Columns:")
print(team_stats.columns)
print("\nTeam Stats Rows:")
print(len(team_stats))
print("\nTeam Stats Missing Values:")
print(team_stats.isnull().sum())
print("-"*50)
print("\nAdvanced Stats Sample:")
print(advanced_stats.head())
print("\nAdvanced Stats Description:")
print(advanced_stats.describe())
print("\nAdvanced Stats Columns:")
print(advanced_stats.columns)
print("\nAdvanced Stats Rows:")
print(len(advanced_stats))
print("\nAdvanced Stats Missing Values:")
print(advanced_stats.isnull().sum())
print("-"*50)
print("\nAll Players Sample:")
print(all_players.head())
print("\n All Players Description:")
print(all_players.describe())
print("\n All Players Columns:")
print(all_players.columns)
print("\n All Players Rows:")
print(len(all_players))
print("\n All Players Missing Values:")
print(all_players.isnull().sum())
print("-"*50)
print("\nAll Teams Sample:")
print(all_teams.head())
print("\n All Teams Description:")
print(all_teams.describe())
print("\n All Teams Columns:")
print(all_teams.columns)
print("\n All Teams Rows:")
print(len(all_teams))
print("\n All Teams Missing Values:")
print(all_players.isnull().sum())
print("-"*50)
print("Data Checks:")
print("\nTop 10 Scorers:")
print(f"{player_stats.sort_values(by='PTS', ascending=False).head(10)[['PLAYER_NAME', 'PTS','FG_PCT']]}")
print(f"\nPlayers with less than 5 games: {len(player_stats[player_stats['GP'] < 5])}")
